### ISSUE TITLE
I get an error with ContOS 7

### ISSUE THREAD

**Issue by webhostpros** [PeachFlame/cPanel-fixperms#3]
./fixperms.sh: line 24: $'\r': command not found
./fixperms.sh: line 25: $'\r': command not found
./fixperms.sh: line 28: $'\r': command not found
./fixperms.sh: line 29: $'\r': command not found
./fixperms.sh: line 31: syntax error near unexpected token `$'{\r''
'/fixperms.sh: line 31: `helptext () {

**Comment by boomshadow** [comment]
I just spun up a cPanel box running Centos7. I didn't have any errors running the script.
Looks like something got changed when you placed the script on your server. That error message you got is indicative of a Windows/Linux end of line conversion issues. Check out this answer over on StackOverflow:
http://stackoverflow.com/a/18608462/2785592
