### ISSUE TITLE
ignore cpanel user system

### ISSUE THREAD

**Issue by MDHMatt** [PeachFlame/cPanel-fixperms#6]
script gets stuck in loop with the cpanel user system.

from the script output;

Fixing perms for system:
------------------------
Fixing website files....
find: ‘/public_html’: No such file or directory
find: ‘/public_html’: No such file or directory
find: ‘/public_html’: No such file or directory
chown: invalid user: ‘system:system’
chown: invalid user: ‘system.system’
chown: invalid user: ‘system.system’
chown: invalid user: ‘system.system’
........ etc

**Comment by boomshadow** [comment]
I just tested this for myself and was able to replicate the problem. Thanks for pointing this out!  
Interestingly, it also picked up an old, terminated cPanel user. Per some of the cPanel staff posts on their forums, there is better ways of getting the list of users than `/var/cpanel/users`.

I'll submit a fix shortly.
